### ISSUE TITLE
Trigger endpoint auth issue

### ISSUE THREAD

**Issue by ajagnanan** [octoblu/meshblu#123]
I was testing triggering a flow with this command:
```
curl -X POST https://triggers.octoblu.com/flows/XX/triggers/XX
```
with no auth headers and it worked. Is that supposed to happen?

**Comment by brianehlert** [comment]
Posting to a trigger does not require authentication. It is simply an incoming message to an obscure endpoint.

**Comment by ajagnanan** [comment]
oh, wouldn't it be better to secure it with meshblu_auth_uuid and meshblu_auth_token in case those endpoints get compromised?

**Comment by brianehlert** [comment]
There are arguments for either way.
Personally, since the trigger is a flow, I filter on the content of the message to ensure that it is what is expected. 
There are other operators such as change, debounce, etc.

IMHO, if someone guesses yurt trigger URL (with two random UUIDs), that is pretty good.

**Comment by ajagnanan** [comment]
I was thinking of adding a token to the payload in order to verify it. Thanks for responding. I'll close out ticket.
