### ISSUE TITLE
/devices/<uuid> endpoint returns Array

### ISSUE THREAD

**Issue by sqrtofsaturn** [octoblu/meshblu#85]
Should return a single device.

Expected Return Value:
```json
    {"uuid": "", "token": ""} 
```
Actual Return Value:
```json
    {"devices": [{"uuid": "", "token": ""}] }
```

**Comment by ra4king** [comment]
This looks like it has been fixed with /v2/devices/:uuid https://github.com/octoblu/meshblu/blob/master/lib/setupHttpRoutes.js#L217

This issue is with /devices/:uuid https://github.com/octoblu/meshblu/blob/master/lib/setupHttpRoutes.js#L190

I don't think they want to break existing applications by changing older API... but considering we're still in beta, I don't see the point of /v2/devices/:uuid

**Comment by iamruinous** [comment]
all new behavior is being moved to versioned api endpoints to make integration easier and more reliable.
